name: "GCP on-demand container scan"
description: "Scan container using GCP"

inputs:
  containerTag:
    description: "Container name tag which we want to scan"
    required: true
  slackWebhook:
    description: "Preferred slack channel webhook to send notifications"
    required: true
  githubUrl:
    description: "Github Action github url"
    required: true
runs:
  using: composite
  steps:
    - name: Add GITHUB run path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH

    - name: Container Scan
      run: ./scripts/scan.sh
      shell: bash
      env:
        containerTag: ${{ inputs.containerTag }}
        slackWebhook: ${{ inputs.slackWebhook }}
        githubUrl: ${{ inputs.githubUrl }}
